"metadata":
  "name": "threatmgmt"
  "namespace": "cp4s"
"spec":
  "acceptLicense": true
  "basicDeploymentConfiguration":
    "adminUser": "admin"
    "domain": ""
    "storageClass": ""
  "extendedDeploymentConfiguration":
    "airgapInstall": false
    "backupStorageClass": ""
    "backupStorageSize": ""
    "imagePullPolicy": "Always"
    "repository": "cp.icr.io/cp/cp4s"
    "repositoryType": "entitled"
    "roksAuthentication": "false"
  "threatManagementCapabilities":
    "deployDRC": true
    "deployRiskManager": true
    "deployThreatInvestigator": true

