apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4s
spec:
  encryptedData:
    .dockerconfigjson: AgA+8UWaeRKymewt6oiTOQjZpPLi5t89PsFz08/pzSViNderCUkbVzx/vxOPRBKqezV6DMJvLTocMACVG9D9cgCUNvURPvtKs4AlZhI/hMsfSetc860sxuRgy/ImJYRDYgiEGAGznxwVufWx91GIshcSCMPcD2mBZqdRcoHS/k7A6Z/Si18jQaRshPcqTb6aw88R9CBKFR5bVT7QD/IZcdcVwI6YFgOH50Nq4tBVSppIFNIOLbTkWlhXiGPz+l0Nq4qsRjUbzDQbxySfoAK272x7awFINpd2Y5U8I38cjQUv6RxrmUL9wVCUya4L2u0LZO6QYrZyzi5Xqnkt5fdfNcG9tSoCwAz+6rDcFt5cSk2ezYClsGFJUnvfW3z+8JkNkW7jjeF0zREQWgYJGlvfUQtaT3zEZEoPNfdCgY61ccHGSQbvCi6tWxKJPdY+zvmcCR1dfRjhQNPOIll9Ye+1NNXx9LMnfjcmAzqYa0un5VjPWbo4217nZbh89pP8+xPA8h8NKAXB9z8ArIuaWUj78Vpv36gKrmqz/s8Kna4spWubLYxdwDeGcN5XXuvucNEtAMPC3zQ68WqH0gc8RPEe0ZmvBVxEoFvfHNGjpFuEMNan54SY+i9kLYLue4AGr+96s04lRJiuYePU4JlWo5P35AW3NNWnc2ij3AUfISTC9BAS4Ao/1c7VHo7qQTducZZaVvYMVKTXg5U81Qq0UIbF5a6bItNIrRUI/SMe4PRuTP8jcJE0nG3p7jeVAVYyLaLo/NqjfXU8yYB31EKxrgaODQMm9+x/rv5BBZF/4P/mw+5UQ0eoVv9OT8uZqJF5vXy5YR7+K974jHvvjWGMdgKJrD0zJJUj8YHx35DUmW2iLzWDsOUwrwg05yBJoDB6HXsST5/Pr/QA++7sLUBN9W3Fb99WPpsGZZIcOPoEELx+Ouit3UldFzKfj/GJilgOJ3aWa+GWNuUFMtqp32Fp2YmYqvZmLyAdmvlsXQhiLVF8Dviz6rO7jso5bPXAbwZaB0brN5DyTfdLaFdq+9SOjsSaZSHNtq4xy/SY+4jZnwTQOrS02bC8sdHg4McKqtxsPi8edU/PMBd3MKQSR9UhTXZj8h2q/b5JQw6gUa53ZOZ6nU9M2tGXGLwuLWZ6quEjSNEtJeFkqbh5dogqx84mdV6ZV86uZBWMNb9mQsNmze+IbNT8ADiRRJfQThNdhfgOFGqJ9G3MnUD6DAKaHpxIl6ILK6CBwG6YuIbUjwIhjW6GSlioHTOkc/94TWlwX1cF0Rdrn9dbmYCc6Q4Bd1TetD8reSa2E62XG8W71CUT+Paco74Wya/0IzQiheQS92GomIw34dWo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4s
    type: kubernetes.io/dockerconfigjson

